name: linkup
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  google_fonts: ^4.0.4 # Corrected placement
  firebase_core: ^3.12.1
  firebase_auth: ^5.5.1
  cloud_firestore: ^5.6.5
  cloudinary_url_gen: ^1.0.0
  cloudinary_api: ^1.0.0
  dio: ^5.8.0+1
  image_picker: ^1.1.2
  flutter_dotenv: ^5.2.1
  cached_network_image: ^3.4.1
  shared_preferences: ^2.5.3
  change_app_package_name: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/profile.jpg
    - assets/logo.png
    - assets/march.png
    - assets/tech.png
    - assets/data.png
    - assets/map.png
    - assets/large.png
    - assets/notifi.png
    - assets/about.png
    
